name: Cocotb Test

on:
  push:
    branches:
      - master  
    paths-ignore:               
      - "out/**" 
      - "resources/**" 
      - ".gitignore"
      - "chn"
      - "README.md"
  pull_request:
    branches:
      - master  
    paths-ignore:               
      - "out/**" 
      - "resources/**" 
      - ".gitignore"
      - "chn"
      - "README.md"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        sudo apt-get update -q
        sudo apt-get install -y iverilog
        pip install cocotb

    - name: Run Cocotb Test
      working-directory: testbench/cocotb  # Subsequent step will back to root directory automatically  
      run: 
        make -f Makefile all

    - name: Clean up
      working-directory: testbench/cocotb
      run:
        make -f Makefile cleanup